// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFBkbEQL5SehSaEiDdggWyLMfUwve9Yp8',
    appId: '1:134772823569:web:27c4a14d1f480ec578c3b0',
    messagingSenderId: '134772823569',
    projectId: 'fir-login-a19bc',
    authDomain: 'fir-login-a19bc.firebaseapp.com',
    storageBucket: 'fir-login-a19bc.appspot.com',
    measurementId: 'G-E6PCVCYMWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLeJn68s9_Ls4VanyjCZY9BQyAO6w0mY',
    appId: '1:134772823569:android:e2b4e9c093d6cd4378c3b0',
    messagingSenderId: '134772823569',
    projectId: 'fir-login-a19bc',
    storageBucket: 'fir-login-a19bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnMgyY8SgmCYoOzoerEezpiguibnR2hXQ',
    appId: '1:134772823569:ios:c1d20243867ace7b78c3b0',
    messagingSenderId: '134772823569',
    projectId: 'fir-login-a19bc',
    storageBucket: 'fir-login-a19bc.appspot.com',
    iosClientId: '134772823569-netdg87ejhfub5c6oce4s5i79v4tq2bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnMgyY8SgmCYoOzoerEezpiguibnR2hXQ',
    appId: '1:134772823569:ios:c1d20243867ace7b78c3b0',
    messagingSenderId: '134772823569',
    projectId: 'fir-login-a19bc',
    storageBucket: 'fir-login-a19bc.appspot.com',
    iosClientId: '134772823569-netdg87ejhfub5c6oce4s5i79v4tq2bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselogin',
  );
}
